# Generated by Django 5.0.6 on 2025-11-07 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_tecnico'),
        ('catalogo', '0001_initial'),
        ('clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePaciente', models.CharField(max_length=150)),
                ('fechaRecepcion', models.DateTimeField()),
                ('fechaEntrega', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acuenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=50)),
                ('detalleTrabajo', models.TextField(blank=True)),
                ('cubeta', models.CharField(blank=True, max_length=50)),
                ('stl', models.CharField(blank=True, max_length=50)),
                ('rMordida', models.CharField(blank=True, max_length=50)),
                ('antagonista', models.CharField(blank=True, max_length=50)),
                ('grafico1', models.IntegerField(blank=True, null=True)),
                ('grafico2', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('dentista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='clinica.dentista')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_tecnico', to='accounts.tecnico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('fechaEntrega', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='ordenes.orden')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.especialidad')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especiales', to='ordenes.orden')),
                ('subespecialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.subespecialidad')),
            ],
        ),
    ]
